version: '2'
services:
  mdbook:
    image: crimsoncorelabs/mdbook
    container_name: mdbook
    restart: unless-stopped
    volumes:
    - /Users/luks/_code/wiki:/opt/wiki
    ports:
      - 3333:3000
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
